# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Math 203
tagline:          'BCC - Math 203'
description:      'Intermediate Algebra'
url:              http://gastonsanchez.com/math203
baseurl:          http://gastonsanchez.com/math203

author:
  name:           'Gaston Sanchez'
  url:            http://gastonsanchez.com

paginate:         5

# Custom vars
version:          Fall 2016

github:
  repo:           https://github.com/gastonstat/math203
